### ISSUE TITLE
GTX 1650 not supported

### ISSUE THREAD

**Issue by xperi-developer** [EmbarkStudios/kajiya#36]
**Describe the bug**
The description says that GTX 1060 and newer are supported (with slow, driver-emulated ray-tracing) but the GTX 1650 does not seem to work, with a thread panic at run-time.

**To Reproduce**
1. Follow the building and running instructions
2. Type `build_and_run.cmd battle`

**Expected behavior**
Demo should run successfully.

**Screenshots**
Compilation succeeds but the following is output when running:

```
    sparse_properties: PhysicalDeviceSparseProperties {
        residency_standard2_d_block_shape: 1,
        residency_standard2_d_multisample_block_shape: 1,
        residency_standard3_d_block_shape: 1,
        residency_aligned_mip_size: 0,
        residency_non_resident_strict: 1,
    },
} }
thread 'main' panicked at 'Device extension not supported: VK_KHR_pipeline_library', crates\lib\kajiya-backend\src\vulkan\device.rs:220:21
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:100
   2: kajiya_backend::vulkan::device::Device::create
             at .\crates\lib\kajiya-backend\src\vulkan\device.rs:220
   3: kajiya_backend::vulkan::RenderBackend::new<winit::window::Window>
             at .\crates\lib\kajiya-backend\src\vulkan\mod.rs:89
   4: kajiya_simple::main_loop::SimpleMainLoop::build
             at .\crates\lib\kajiya-simple\src\main_loop.rs:235
   5: kajiya_simple::main_loop::SimpleMainLoopBuilder::build
             at .\crates\lib\kajiya-simple\src\main_loop.rs:154
   6: view::main
             at .\crates\bin\view\src\main.rs:112
   7: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\view.exe --scene battle --width 1920 --height 1080 --no-debug` (exit code: 101)
```

**Device:**
 - OS: Windows 11 Home Insider Preview (22523.1000)
 - Card: NVIDIA GeForce GTX 1650
 - Driver: Latest Game Ready Driver (497.29)
 - Toolchain: stable-x86_64-pc-windows-msvc (default)
 - Visual Studio 2019 (16.10.4)
 - rustc 1.57.0 (f1edd0429 2021-11-29)

**Additional context**
Perhaps this graphics card is simply not supported, in which case more clarity about supported graphics cards would be useful.

**Comment by h3r2tic** [comment]
Thanks for all the details! The interwebs are rather confusing about whether the 1650 should work or not -- some sources say that you need an NV GPU with at least 6GB of VRAM (so for the 16-series, GTX 1660 and up), but then [Nvidia's Vulkan _Beta_ driver page](https://developer.nvidia.com/vulkan-driver) says that 1650 is fine. Perhaps you need the beta driver? Otherwise I suspect we're out of luck...

**Comment by lnicola** [comment]
FWIW, `radv` and `mesa` itself are also missing that extension.

**Comment by bestouff** [comment]
Yes, I have a GTX 1650 using Mesa, and got the same error. Is that intended to work one day on Mesa, or is hope lost on that ?

**Comment by xperi-developer** [comment]
> Thanks for all the details! The interwebs are rather confusing about whether the 1650 should work or not -- some sources say that you need an NV GPU with at least 6GB of VRAM (so for the 16-series, GTX 1660 and up), but then [Nvidia's Vulkan _Beta_ driver page](https://developer.nvidia.com/vulkan-driver) says that 1650 is fine. Perhaps you need the beta driver? Otherwise I suspect we're out of luck...

I tried the Vulkan beta driver (472.85) as suggested, but I get the same error message. The preamble is as follows:
```
    Finished release [optimized + debuginfo] target(s) in 3m 42s
     Running `target\release\view.exe --scene battle --width 1920 --height 1080 --no-debug`
[2021-12-29 16:46:32][kajiya_simple::main_loop][INFO] Internal rendering extent: 1920x1080
[2021-12-29 16:46:32][kajiya_backend::vulkan::instance][INFO] Created a Vulkan instance
[2021-12-29 16:46:32][kajiya_backend::vulkan][INFO] Available physical devices: [
    "AMD Radeon(TM) Graphics",
    "NVIDIA GeForce GTX 1650",
]
[2021-12-29 16:46:32][kajiya_backend::vulkan][INFO] Selected physical device: PhysicalDevice { PhysicalDeviceProperties {
    api_version: 4202696,
    driver_version: 1981104128,
    vendor_id: 4318,
    device_id: 8089,
    device_type: DISCRETE_GPU,
    device_name: "NVIDIA GeForce GTX 1650",
```

**Comment by xperi-developer** [comment]
I also tried forcing `view.exe` to use 'High performance' graphics (i.e. the GTX 1650) in Settings | System | Display | Graphics but it made no difference.

**Comment by vikasTmz** [comment]
I get the same error on GeForce RTX 2060.

**Comment by h3r2tic** [comment]
@xperi-developer 
> I tried the Vulkan beta driver (472.85) as suggested, but I get the same error message. (...)

That is unfortunate... Thank you for testing though! 💖
Guess 1650 will be officially unsupported then 😢

@vikasTmz 
> I get the same error on GeForce RTX 2060.

That is unexpected though. It should definitely work on a 2060. Are you running recent Nvidia drivers? Do any other ray-tracing apps/samples work for you?

@lnicola 
> FWIW, `radv` and `mesa` itself are also missing that extension.

Looks like ray tracing is very new in Mesa, so could be patchy... Similarly to the above in general -- if anything else using ray-tracing works for you, it's going to be a `kajiya` bug -- otherwise a driver issue.

**Comment by h3r2tic** [comment]
I've clarified the README now. It seems that the emulated ray tracing support for non-RTX Nvidia GPUs is only enabled by the driver for models with 6 or more gigabytes of memory. Even though 1650 is newer than 1060, the latter is faster and comes in 6 GB variants. Will update the README if the situation changes, or if we get any success reports from GTX 1650.
