### ISSUE TITLE
Particle Effects

### ISSUE THREAD

**Issue by gotzl** [EmbarkStudios/kajiya#39]
First, thanks for open-sourcing (some of) your stuff! I took Cornell McRay as a nudge to learn Rust and I started porting a game I devel'd once. So far it's working really great!
Since the game used particle effects, I'd like to port them as well, but I realize that this feature is not yet built into kajiya.

So my question is, do you plan to implement (a system for, or hooks for) particle effects at some point?
If not, could you comment on the feasibility to implement this in kajiya? Or maybe even draft a very crude list of 'things that have to be done' to implement this? Then I would maybe try to do it ...

Thanks!

**Comment by h3r2tic** [comment]
👀

That... depends 😅 Particles/vfx are a huge subject. Are you okay with opaque ones? Otherwise it means transparency, and transparency is hell...
