### ISSUE TITLE
Interior rendering lighting changes based on world position

### ISSUE THREAD

**Issue by dtrebilco** [EmbarkStudios/kajiya#40]
**Describe the bug**
It seems that interior areas are well lit and do not match the reference at all when at different world positions.

I am attempting to render a house and at the origin it renders correctly (according to the reference - light not coming through windows is a different issue)
![Interior](https://user-images.githubusercontent.com/7506147/149049912-58b571f0-3eb0-42d0-b9f5-aad1d05b576f.jpg)

Walking down the house (scale is 1 unit = 1m in case that makes a difference) there is a transition area where light is coming from "somewhere"
![Transition](https://user-images.githubusercontent.com/7506147/149050058-51a7757e-1ddd-4b45-a1d7-398e39cfbeb9.jpg)

Here is the reference of that area
![Transition_ref](https://user-images.githubusercontent.com/7506147/149050064-d1a759e8-82ac-4b35-88cd-480db5c0b31a.jpg)

Until the front rooms are fully lit
![FrontRoom](https://user-images.githubusercontent.com/7506147/149050114-1593bf39-aa49-43c0-8563-92aecdd9d01e.jpg)

Reference:
![FrontRoom_ref](https://user-images.githubusercontent.com/7506147/149050125-360044ea-fc13-42c4-a9d8-9d1c29627509.jpg)

If I move the house in the scene file (say by 10m), the lit areas move around the house

I am guessing that perhaps there is some setting where interior lighting is only performed correctly at some small distance from the origin? Or perhaps there is some world light that starts at this position?

Let me know if it would be helpful to have the sample data - I will see if I can get permission to supply a cut down version.

**Device:**
 - OS: Windows 10
 - Version: Git sysnch of 10 January 2022

**Comment by h3r2tic** [comment]
Cool scene!

This one is the fixed-size GI volume scale that `README.md` mentions:

> * The voxel GI uses a fixed-size volume around the origin by default.
>     * Use `--gi-volume-scale` to change its extent in the `view` app
>     * It can be configured to use camera-centered cascades at an extra performance cost (see `CASCADE_COUNT` and `SCROLL_CASCADES` in csgi.rs)

Try with, say, `--gi-volume-scale 2`, then see if it's still there, and if not, go higher.

**Comment by dtrebilco** [comment]
Thanks that works fine - sorry I missed that in the readme.

**Comment by h3r2tic** [comment]
No worries! Hope the parameter worked out fine 😄
