### ISSUE TITLE
Normal map exists but reliefs are missing

### ISSUE THREAD

**Issue by SamuelTallet** [EmbarkStudios/kajiya#49]
Hello,

First thing, thanks for your awesome work!
I have an issue with [this glTF model](https://github.com/EmbarkStudios/kajiya/files/8048970/T-Rex.gltf.zip). According to [glTF Report app](https://gltf.report/) the model is valid:

![T-Rex - glTF Report - Valid](https://user-images.githubusercontent.com/36248671/153601634-523574df-e21e-4e7e-8026-250b4859c215.png)

Its reliefs appear:

![T-Rex - glTF Report](https://user-images.githubusercontent.com/36248671/153601715-739ff33f-c5e2-428a-98b8-54a962624adb.png)

But Kajiya seems to ignore its normal map:

![T-Rex - Kajiya](https://user-images.githubusercontent.com/36248671/153601783-46522731-87ee-4cb0-886b-45e824864f4b.png)

Technical details:
- Kajiya (latest)
- Windows 10
- GTX 1060 6GB

**Comment by h3r2tic** [comment]
Hey! Looks like the asset is missing vertex tangents, which are needed for normal mapping, and which kajiya does not auto-generate right now.

**Comment by SamuelTallet** [comment]
Thanks for your quick reply! Is tangents auto generation planned?

**Comment by SamuelTallet** [comment]
I don't know if it can help... A [Rust implementation of Mikkelsen Tangent Space Algorithm](https://crates.io/crates/mikktspace) exists.

**Comment by h3r2tic** [comment]
Yup, that was very easy to plug in, thanks 😀

![image](https://user-images.githubusercontent.com/16522064/153704176-ee86ab77-083b-4623-b13b-c17f25ff8555.png)

Still lacks feathers, but I guess we can tackle biological accuracy in another issue 😜

**Comment by SamuelTallet** [comment]
Great! Thanks.
