### ISSUE TITLE
Non-QWERTY keyboards

### ISSUE THREAD

**Issue by SamuelTallet** [EmbarkStudios/kajiya#51]
Hello,

I have an AZERTY keyboard and it's difficult for me to navigate in the scene since the `view` app expects a QWERTY keyboard 😅<br>
Here are solutions which could solve this issue:

### Solution A

Use `scancode` instead of `virtual_keycode` for the `Q`, `W` and `A` letters.

> scancode: [ScanCode](https://docs.rs/winit/0.25.0/winit/event/type.ScanCode.html)
>
> Identifies the physical key pressed
> This should not change if the user adjusts the host’s keyboard map. Use when the physical location of the key is more important than the key’s host GUI semantics, such as for movement controls [...]

According to [Keyboard Layout Info](https://kbdlayout.info/), scancodes we need are identical for [UK](https://kbdlayout.info/KBDUK/scancodes) and [FR](https://kbdlayout.info/KBDFR/scancodes) keyboards, for instance, but I'm not sure about cross-platformness and hardware variants!

### Solution B

Read the keyboard mapping from a TOML configuration file. For instance:

```toml
[keymap]
# move_fwd = "W" # QWERTY
move_fwd = "Z" # AZERTY
move_back = "S" # QWERTY & AZERTY
# and so on.
```

This opens the way to mapping of mouse buttons in a configuration file but let's refocus on keyboard 😉

### Solution C

Add an optional `--keyboard` CLI argument with the default value: `qwerty`<br>
Keyboard layout would be detected in third-party program with [Win32 API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutnamea), for instance, or asked directly to user in third-party program. Kajiya would just need to map keys according to the value of `--keyboard`:

| **keyboard** | **move_fwd** | **move_back** | **move_left** | **move_right** | **move_down** | **move_up** |
|--------------|--------------|---------------|---------------|----------------|---------------|-------------|
| qwerty       |       W      |       S       |       A       |        D       |       Q       |      E      |
| azerty       |       Z      |       S       |       Q       |        D       |       A       |      E      |

**Comment by h3r2tic** [comment]
Hah, I use the Colemak layout, so I certainly feel this as well 😀 The `view` app is a small toy though, and not a real app -- if you'd like to contribute an improvement, a PR would be most welcome!

**Comment by SamuelTallet** [comment]
I like this `view` app because it's minimal 😄 I was looking for a renderer with an UI hidden by default. Perfect for plugins👌<br>
How do you deal with the Colemak layout? Do you change keyboard settings in your OS to match with the QWERTY layout?

**Comment by h3r2tic** [comment]
I have a custom Rust app which remaps my keys on the fly (it goes deeper than just Colemak 😅), and supports a chord to flip back to Qwerty.
