### ISSUE TITLE
Downloading SPIR-V shaders

### ISSUE THREAD

**Issue by kvark** [EmbarkStudios/kajiya#53]
**Is your feature request related to a problem? Please describe.**
I'd like to use some of the Kajiya shaders for testing. I need SPIR-V, and it appears to be a build product of the game.

**Describe the solution you'd like**
Perhaps, an attachment to a release with all the SPIR-V files zipped? Could even be done automatically, but I need it once so far.

**Describe alternatives you've considered**
I can try to extract it myself, but I haven't done anything with the project yet.

**Additional context**
This is for https://github.com/kvark/shader-translation-benchmark

**Comment by h3r2tic** [comment]
Howdy!

`kajiya` doesn't really have releases right now, and releasing the SPIR-V is not particularly relevant to the project... However! The SPIR-V for Rust shaders is already available in https://github.com/EmbarkStudios/kajiya/tree/main/assets/rust-shaders-compiled, and SPIR-V for the HLSL shaders is super simple to dump:

```diff
diff --git a/crates/lib/kajiya-backend/src/shader_compiler.rs b/crates/lib/kajiya-backend/src/shader_compiler.rs
index 00ed5c9..f0d17b9 100644
--- a/crates/lib/kajiya-backend/src/shader_compiler.rs
+++ b/crates/lib/kajiya-backend/src/shader_compiler.rs
@@ -189,6 +189,8 @@ fn compile_generic_shader_hlsl_impl(
     )
     .map_err(|err| anyhow!("{}", err))?;
 
+    std::fs::write(format!("compiled_shaders/{name}.spv"), &spirv).unwrap();
+
     log::trace!("dxc took {:?} for {}", t0.elapsed(), name,);
 
     Ok(spirv.into())
```

With this, upon launching the `view` app, all the HLSL shaders will be written out.

Here's the output of that for your convenience:
[compiled_shaders.zip](https://github.com/EmbarkStudios/kajiya/files/8148635/compiled_shaders.zip)
