### ISSUE TITLE
Gifts: kajiya splash screen and app icon

### ISSUE THREAD

**Issue by SamuelTallet** [EmbarkStudios/kajiya#54]
Hello,

I made a splash screen and a logo (declined in icon) for `kajiya`. If you like them, they are yours! 😉🎁

![kajiya splash screen](https://user-images.githubusercontent.com/36248671/154961518-c5b92aec-1753-48d6-a9b1-3c9609f44d1f.png)

![kajiya splash screen 16:9](https://user-images.githubusercontent.com/36248671/154961720-dfb7819c-6f3e-454b-9071-60cb66849af8.png)

<p>
  <img src="https://user-images.githubusercontent.com/36248671/154961790-99c58d9f-c94a-421b-9a35-0c446c2ec4aa.png" width="32%" />
  <img src="https://user-images.githubusercontent.com/36248671/154961813-f1ea72c4-c88e-4236-a163-5237e8b1d3ad.png" width="32%" /> 
  <img src="https://user-images.githubusercontent.com/36248671/154961832-5006ac8b-6dc3-4bc3-bce8-624c7559d065.png" width="32%" />
</p>

**Credits**

- “Burst Style Text Effect Mockup“ PSD template, by [Sdecoret](https://sdecoret.myportfolio.com/), licensed under [Adobe Stock Extended](https://stock.adobe.com/license-terms).
- “TRON“ font, by Paul Albers, licensed under Freeware (Free both for commercial and personal use).

**Comment by h3r2tic** [comment]
Hey! Thank you for this 😀 Some serious retro vibes here! It's a cool look, but not one that I will use for `kajiya` -- I'm already working with a graphics designer colleague of mine to create a logo for the project. (We're going after the Japanese meaning of the word 👀)
