### ISSUE TITLE
compiling view 0.1.0 on win10

### ISSUE THREAD

**Issue by nassosyian** [EmbarkStudios/kajiya#55]
i get the following error with the latest build

`   Compiling view v0.1.0 (c:\kajiya\crates\bin\view)
error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:146:33
    |
146 |             .with(Position::new(position))
    |                                 ^^^^^^^^ expected struct `dolly::glam::Vec3`, found struct `kajiya_simple::Vec3`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:147:49
    |
147 |             .with(YawPitch::new().rotation_quat(rotation))
    |                                                 ^^^^^^^^ expected struct `dolly::glam::Quat`, found struct `kajiya_simple::Quat`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:195:30
    |
195 |             camera_position: camera.final_transform.position,
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `kajiya_simple::Vec3`, found struct `dolly::glam::Vec3`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:196:30
    |
196 |             camera_rotation: camera.final_transform.rotation,
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `kajiya_simple::Quat`, found struct `dolly::glam::Quat`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0277]: cannot multiply `dolly::glam::Quat` by `kajiya_simple::Vec3`
   --> crates\bin\view\src\main.rs:236:17
    |
236 |                 * Vec3::new(input["move_right"], input["move_up"], -input["move_fwd"])
    |                 ^ no implementation for `dolly::glam::Quat * kajiya_simple::Vec3`
    |
    = help: the trait `Mul<kajiya_simple::Vec3>` is not implemented for `dolly::glam::Quat`

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:250:37
    |
250 |             state.camera_position = camera.final_transform.position;
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `kajiya_simple::Vec3`, found struct `dolly::glam::Vec3`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:251:37
    |
251 |             state.camera_rotation = camera.final_transform.rotation;
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `kajiya_simple::Quat`, found struct `dolly::glam::Quat`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:295:44
    |
295 |                         .set_rotation_quat(state.camera_rotation);
    |                                            ^^^^^^^^^^^^^^^^^^^^^ expected struct `dolly::glam::Quat`, found struct `kajiya_simple::Quat`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0308]: mismatched types
   --> crates\bin\view\src\main.rs:296:64
    |
296 |                     camera.driver_mut::<Position>().position = state.camera_position;
    |                                                                ^^^^^^^^^^^^^^^^^^^^^ expected struct `dolly::glam::Vec3`, found struct `kajiya_simple::Vec3`
    |
    = note: perhaps two different versions of crate `glam` are being used?

error[E0599]: the method `through` exists for tuple `(dolly::glam::Vec3, dolly::glam::Quat)`, but its trait bounds were not satisfied
   --> crates\bin\view\src\main.rs:373:22
    |
373 |                     .through(&lens),
    |                      ^^^^^^^ method cannot be called on `(dolly::glam::Vec3, dolly::glam::Quat)` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `(dolly::glam::Vec3, dolly::glam::Quat): IntoCameraBodyMatrices`
            which is required by `(dolly::glam::Vec3, dolly::glam::Quat): kajiya_simple::LookThroughCamera`
            `&(dolly::glam::Vec3, dolly::glam::Quat): IntoCameraBodyMatrices`
            which is required by `&(dolly::glam::Vec3, dolly::glam::Quat): kajiya_simple::LookThroughCamera`
            `&mut (dolly::glam::Vec3, dolly::glam::Quat): IntoCameraBodyMatrices`
            which is required by `&mut (dolly::glam::Vec3, dolly::glam::Quat): kajiya_simple::LookThroughCamera`

Some errors have detailed explanations: E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `view` due to 10 previous errors`

**To Reproduce**
1. download the latest build (commit [07218ed])
2. `bake`
3. `build_and_run.cmd conference`

**Expected behavior**
To have no errors and run.

**Device:**
 - OS: Win10 Pro x64 (v.21H2, build 19044.1526)
 - Browser: chrome
 - Version: 99.0.4844.51

**Comment by h3r2tic** [comment]
Hmm, I can't repro this -- if you run `git diff`, do you have any local changes in `Cargo.lock`?

**Comment by SamuelTallet** [comment]
I successfully build latest `kajiya` version with MSVC toolchain on Windows 11. @nassosyian Do you use GNU or MSCV toolchain?

**Comment by nassosyian** [comment]
@h3r2tic deleted the old folder and re-downloaded the repo, compiles just fine now. Must have run `cargo update` at some point in the past.
@SamuelTallet i use the MSVC toolchain.

When i run `build_and_run.cmd conference`
the window shows up with the scene (which is way too dark), 
i get the following (non-critical) error :
`[2022-03-12 14:26:00][kajiya_backend::rust_shader_compiler][ERROR] Failed to build Rust-GPU shaders. Falling back to the previously compiled ones. Error: Shader builder failed:

error: the 'cargo.exe' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2021-09-29-x86_64-pc-windows-msvc' toolchain`

![image](https://user-images.githubusercontent.com/3863843/158017965-7810a831-c0ec-4760-b7c4-274af7a29e16.png)

**Comment by SamuelTallet** [comment]
@nassosyian You can try to switch to a more recent and stable MSVC toolchain with:

```shell
rustup toolchain remove nightly-x86_64-pc-windows-msvc
rustup toolchain install stable-x86_64-pc-windows-msvc
```

**Comment by h3r2tic** [comment]
> @h3r2tic deleted the old folder and re-downloaded the repo, compiles just fine now.

Cool!


> When i run `build_and_run.cmd conference` the window shows up with the scene (which is way too dark),

It's a dark scene 😛 But happy to hear it works!


> i get the following (non-critical) error : `[2022-03-12 14:26:00][kajiya_backend::rust_shader_compiler][ERROR] Failed to build Rust-GPU shaders. Falling back to the previously compiled ones. Error: Shader builder failed:
> 
> error: the 'cargo.exe' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2021-09-29-x86_64-pc-windows-msvc' toolchain`

That's safe to ignore. It means that you don't have the Rust version necessary to iterate on `rust-gpu` shaders, but everything will work fine 😀

**Comment by nassosyian** [comment]
@SamuelTallet @h3r2tic 
thank you both
