### ISSUE TITLE
Can't debug with renderdoc

### ISSUE THREAD

**Issue by chena1982** [EmbarkStudios/kajiya#62]
Windows 11, GPU is 3080.
If i run from cmd shell, everything is ok.
If i use renderdoc to launch view.exe, the shading mode auto set to "RTX OFF", manual set it to "Default" also don't work.

**Comment by hrydgard** [comment]
This is expected - since RenderDoc doesn't yet support raytracing, while running under RenderDoc it's not exposed and it thus falls back to RTX OFF.

**Comment by chena1982** [comment]
Sorry, i make some mistake, thanks for you reply.
