### ISSUE TITLE
not an actual issue, just a question as to how you do something

### ISSUE THREAD

**Issue by Pjbomb2** [EmbarkStudios/kajiya#66]
So first off, this is an amazing project, thank you so much for making it public!
But as for my actual question, I was wondering how you hide the frametime spike that results from 1 out of 3 rays not presenting any new information?
I tried something similar for sample validation for ReSTIR GI, but couldnt figure out how to hide the lag spike effectively, how do you guys do it?
Thank you!!

**Comment by h3r2tic** [comment]
Howdy! Why would there be a frame time spike? The rays that would normally be used for radiance estimation are instead used for validation, so performance stays pretty much the same... Except the short ray tracing which still needs to happen for micro-detail, but I cover that in the write-up.
