### ISSUE TITLE
Incorrect shading coordinate system while raytracing.

### ISSUE THREAD

**Issue by CrystaLamb** [EmbarkStudios/kajiya#72]
**Describe the bug**
In assets/shaders/rt/gbuffer.rchit.hlsl, you computes the texture lod by using ray cone method.
In function compute_texture_lod(), parameter takes surf_normal whichi is computed by the vertices data.
But notice that the lod computation take place in world space, but the surf_normal you passes in is in object space.
This will produce incorrect texture sample! (I test on my own impl in my toy engine)

Fix: add float3 surf_normal_ws = normal(mul(ObjectToWorld3x4(), float4(surf_normal, 0.0)));
then use surf_normal_ws as the input in compute_texture_lod();

This will produce incorrect lod and strange banding effect depends on the view direction.
![incorrect](https://user-images.githubusercontent.com/57090275/209425894-6e205175-d13b-41b4-81e0-7fb442c09c73.png)

This is the correct image.
![correct](https://user-images.githubusercontent.com/57090275/209425895-69abbc2f-b6ff-43af-bae7-f122e824b4b6.png)

**Comment by h3r2tic** [comment]
Aaaand fixed by your PR :partying_face:

Thanks again!

(I loaded up the same model, and reproduced the bug quite easily. Your PR fixes it cleanly)
