### ISSUE TITLE
[Request] A demo for making and rendering a scene natively

### ISSUE THREAD

**Issue by djkato** [EmbarkStudios/kajiya#81]
Love the project, trying to make something with it. Researching how it works, I unfortunately struggle to understand it. A simple demonstration of how to create a simple native scene with the renderer would be amazing. 

As a newbie to both Rust and 3D programming I'd appreciate if it covered something like:
- Create simple scene, maybe just a cube, floor and sky. Ideally natively, without Kajiya-simple or GLTF imports to understand the basics. For use of external assets there's already the car demo.
- Process of setting up the renderer
- Not even making it interactive, but maybe render a single frame to an  image file saved on-disk

I have read through Kajiya-simple and tried to understand how it sets up the rendering, but I'm not there yet.

Thanks, dj

**Comment by h3r2tic** [comment]
I will not have the time to do this personally, but contributions are welcome!

**Comment by djkato** [comment]
Well, I've been looking at the source code, and from looking around it seems WorldRenderer is what I'd use, but the surface is not optional, so window-less rendering would take a lot of work I am under-qualified for.... I will look around the code a bit more to see if I could do it.
