### ISSUE TITLE
Provide binary releases for easy testing

### ISSUE THREAD

**Issue by Calinou** [EmbarkStudios/kajiya#84]
**Is your feature request related to a problem? Please describe.**
I'd like to test this renderer without needing a Rust toolchain and knowledge to compile the `view` application.

**Describe the solution you'd like**
Create precompiled builds using GitHub Actions, and upload them in a tagged release.

**Describe alternatives you've considered**
N/A

**Additional context**
This should ideally cover Windows/macOS/Linux, but covering Windows/Linux would be a good start. Given the high-end focus, providing ARM/x86_32 binaries isn't essential.

**Comment by repi** [comment]
thanks for the interest and request! 
this repository is for meant for developers experimenting and is not a user application so providing pre-built binaries is out of the scope for this
