### ISSUE TITLE
is dis project abandoned

### ISSUE THREAD

**Issue by redgpu** [EmbarkStudios/kajiya#85]
or what. it's awkward that it's under embark's org, our guy doesn't work here anymore, so aaawkwaaard

**Comment by h3r2tic** [comment]
It's not abandoned. It's just... having some alone time to contemplate life, the universe, and everything.

**Comment by repi** [comment]
if only we used some type of source control system that stores everything in an immutable append-only ledger that could be downloaded locally and shared, forked, or merged free at will. then we would be able to preserve this project for long after Embark and GitHub ceases to exist. someone should invent such a thing!
